name: twisted-apidocs

on:
  push:
    branches: [ main ]

jobs:
  twisted:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8

    - name: Install requirements for documentation generation
      run: |
        python -m pip install --upgrade pip setuptools wheel tox

    - name: Generate API documentation
      run: |
        tox -e twisted-apidocs

    - name: Push API documentation to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/twisted/
        commit_message: "Update twisted API documentations"
        destination_dir: twisted
        enable_jekyll: true
